"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import ssl
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from backend/.env
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Default to True for development, set DJANGO_DEBUG=False in production
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() == 'true'

# Optional: disable SSL verification for SendGrid in dev if explicitly requested
# SECURITY WARNING: This should NEVER be enabled in production
if os.environ.get("SENDGRID_SKIP_SSL_VERIFY", "").lower() == "true":
    ssl._create_default_https_context = ssl._create_unverified_context
    # Log warning if used in production
    if not DEBUG:
        import warnings
        warnings.warn(
            "⚠️  SECURITY WARNING: SSL verification is disabled! "
            "This should NEVER be used in production as it makes the application "
            "vulnerable to MITM (Man-in-the-Middle) attacks.",
            UserWarning
        )

# SECURITY WARNING: keep the secret key used in production secret!
# In production, SECRET_KEY must be set via environment variable
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        # Only use default in development
        SECRET_KEY = 'django-insecure-g#z9@_6j&#)fl!x#ymg^71a!n_jv_jpt1yh-_337xpf_n1wx0!'
    else:
        raise ValueError("SECRET_KEY environment variable must be set in production!")

allowed_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts.split(',') if host.strip()]

# Production security check
if not DEBUG and (not SECRET_KEY or SECRET_KEY.startswith('django-insecure-')):
    import warnings
    warnings.warn(
        "⚠️  PRODUCTION WARNING: Using insecure SECRET_KEY in production! "
        "Set DJANGO_SECRET_KEY environment variable with a secure key.",
        UserWarning
    )

# Security settings for production
if not DEBUG:
    # Security headers
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False').lower() == 'true'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Content Security Policy
    # Note: Configure based on your frontend domains
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    
    # Session security
    SESSION_COOKIE_AGE = 3600  # 1 hour
    SESSION_EXPIRE_AT_BROWSER_CLOSE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    
    # CSRF cookie settings
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = 'Lax'
    
    # CSRF trusted origins (required for production)
    # Initialize as empty list, will be set later from CORS_ALLOWED_ORIGINS if needed
    CSRF_TRUSTED_ORIGINS = []
    csrf_trusted_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
    if csrf_trusted_origins:
        CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_trusted_origins.split(',') if origin.strip()]
else:
    # Development: Allow localhost for CSRF
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:3000',
        'http://localhost:3003',
        'http://127.0.0.1:3000',
        'http://127.0.0.1:3003',
    ]


# Application definition

# Check if optional packages are available
try:
    import drf_spectacular
    SPECTACULAR_AVAILABLE = True
except ImportError:
    SPECTACULAR_AVAILABLE = False

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # For token blacklisting
    'corsheaders',
    'api',
    'drf_yasg',
]

# Add drf_spectacular only if available
if SPECTACULAR_AVAILABLE:
    INSTALLED_APPS.insert(-1, 'drf_spectacular')  # Add before 'api'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',  # Response compression
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.middleware.SecurityHeadersMiddleware',  # SECURITY: CSP, Permissions-Policy
    'api.middleware.RequestLoggingMiddleware',  # Request logging
    'api.middleware.RateLimitMiddleware',  # Rate limiting (only in production)
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# PostgreSQL Database Configuration (REQUIRED - Docker only)
# This project uses Docker for PostgreSQL. Local PostgreSQL is NOT allowed.
POSTGRES_HOST = os.environ.get('POSTGRES_HOST', 'localhost')

# Validate that Docker PostgreSQL is being used (not local PostgreSQL)
# Note: If Django runs on host machine, use POSTGRES_HOST=localhost
#       If Django runs in Docker, use POSTGRES_HOST=postgres
# We allow localhost only if it's for Docker container access from host
if POSTGRES_HOST not in ['localhost', '127.0.0.1', 'postgres']:
    raise ValueError(
        f"❌ ERROR: Invalid POSTGRES_HOST value: {POSTGRES_HOST}\n"
        "Valid values: 'localhost' (for host machine access to Docker), 'postgres' (for Docker network)\n\n"
        "See DOCKER_SETUP.md for installation instructions."
    )

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'acurate_db'),
        'USER': os.environ.get('POSTGRES_USER', 'acurate_user'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'acurate_pass_2024'),
        'HOST': POSTGRES_HOST,
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        'OPTIONS': {
            'connect_timeout': 10,
            'options': '-c statement_timeout=30000',  # 30 seconds query timeout
        },
        # Connection pooling for production
        'CONN_MAX_AGE': 600 if not DEBUG else 0,  # 10 minutes in production, 0 in dev
    }
}

# Validate PostgreSQL connection on startup
if DATABASES['default']['ENGINE'] != 'django.db.backends.postgresql':
    raise ValueError(
        "❌ ERROR: This project requires PostgreSQL. SQLite is not supported.\n"
        "Please use Docker PostgreSQL as configured in docker-compose.yml.\n"
        "See DOCKER_SETUP.md for installation instructions."
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 10,  # Production: minimum 10 characters
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    # Custom validator for complexity (uppercase, lowercase, digit, special char)
    {
        'NAME': 'api.validators.PasswordComplexityValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'api.User'

# Email / SendGrid configuration
EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
SENDGRID_API_KEY = os.environ.get('SENDGRID_API_KEY', '')
SENDGRID_SANDBOX_MODE_IN_DEBUG = False
# DEFAULT_FROM_EMAIL should be set via environment variable in production
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'beyza.karasahan@live.acibadem.edu.tr')

# Email validation
if not DEBUG and not DEFAULT_FROM_EMAIL:
    import warnings
    warnings.warn(
        "⚠️  PRODUCTION WARNING: DEFAULT_FROM_EMAIL is not set! "
        "Set DEFAULT_FROM_EMAIL environment variable for email functionality.",
        UserWarning
    )

# --- CORS Ayarları ---
# Development origins
CORS_ALLOWED_ORIGINS_DEV = [
    "http://localhost:3000",   # Next.js dev server
    "http://localhost:3003",   # Alternative port
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3003",
]

# Production origins (add your production domains here)
CORS_ALLOWED_ORIGINS_PROD = os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
CORS_ALLOWED_ORIGINS_PROD = [origin.strip() for origin in CORS_ALLOWED_ORIGINS_PROD if origin.strip()]

# Combine based on DEBUG mode
if DEBUG:
    CORS_ALLOWED_ORIGINS = CORS_ALLOWED_ORIGINS_DEV
else:
    CORS_ALLOWED_ORIGINS = CORS_ALLOWED_ORIGINS_PROD or CORS_ALLOWED_ORIGINS_DEV

# Set CSRF_TRUSTED_ORIGINS from CORS_ALLOWED_ORIGINS if not already set in production
if not DEBUG and len(CSRF_TRUSTED_ORIGINS) == 0:
    CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS

CORS_ALLOW_CREDENTIALS = True

# Additional CORS headers for security
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# --- REST Framework Ayarları ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # Exception handling
    'EXCEPTION_HANDLER': 'api.exceptions.custom_exception_handler',
}

# Add API Documentation schema only if drf-spectacular is available
if SPECTACULAR_AVAILABLE:
    REST_FRAMEWORK['DEFAULT_SCHEMA_CLASS'] = 'drf_spectacular.openapi.AutoSchema'

# --- JWT Ayarları ---
# SECURITY: JWT token configuration with security best practices
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),  # Short-lived access tokens
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Longer refresh tokens
    'ROTATE_REFRESH_TOKENS': True,  # Rotate refresh tokens on each use
    'BLACKLIST_AFTER_ROTATION': True,  # Blacklist old refresh tokens
    'AUTH_HEADER_TYPES': ('Bearer',),
    'UPDATE_LAST_LOGIN': True,  # Track last login time
    'TOKEN_OBTAIN_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenObtainPairSerializer',
    'TOKEN_REFRESH_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenRefreshSerializer',
}

# SECURITY: Maximum concurrent sessions per user (for future implementation)
# Set to 0 to disable limit
MAX_SESSIONS_PER_USER = int(os.environ.get('MAX_SESSIONS_PER_USER', 5))

# --- API Documentation (drf-spectacular) ---
# Only define if drf-spectacular is available
if SPECTACULAR_AVAILABLE:
    SPECTACULAR_SETTINGS = {
        'TITLE': 'AcuRate API',
        'DESCRIPTION': 'Academic Performance Analysis System API Documentation',
        'VERSION': '1.0.0',
        'SERVE_INCLUDE_SCHEMA': False,
        'COMPONENT_SPLIT_REQUEST': True,
        'SCHEMA_PATH_PREFIX': '/api/',
        'AUTHENTICATION_WHITELIST': [
            'rest_framework_simplejwt.authentication.JWTAuthentication',
        ],
        # SECURITY: Restrict API docs in production
        'SERVE_PERMISSIONS': ['rest_framework.permissions.IsAdminUser'] if not DEBUG else ['rest_framework.permissions.AllowAny'],
    }

# SECURITY: Control API docs visibility
API_DOCS_ENABLED = os.environ.get('API_DOCS_ENABLED', 'True' if DEBUG else 'False').lower() == 'true'

# --- Caching Configuration ---
# Use local memory cache for development, Redis for production
CACHE_BACKEND = os.environ.get('CACHE_BACKEND', 'local' if DEBUG else 'redis')

if CACHE_BACKEND == 'redis':
    # Redis cache for production
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 50,
                    'retry_on_timeout': True,
                },
                'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
                'IGNORE_EXCEPTIONS': True,  # Don't crash if cache fails
            },
            'KEY_PREFIX': 'acurate',
            'TIMEOUT': 300,  # Default timeout: 5 minutes
        }
    }
else:
    # Local memory cache for development
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'acurate-cache',
            'TIMEOUT': 300,  # Default timeout: 5 minutes
            'OPTIONS': {
                'MAX_ENTRIES': 1000,
            }
        }
    }

# Cache key prefixes
CACHE_KEY_PREFIX = 'acurate'
CACHE_TIMEOUT_SHORT = 60  # 1 minute - for frequently changing data
CACHE_TIMEOUT_MEDIUM = 300  # 5 minutes - default
CACHE_TIMEOUT_LONG = 3600  # 1 hour - for relatively static data
CACHE_TIMEOUT_ANALYTICS = 600  # 10 minutes - for analytics/dashboard data
CACHE_TIMEOUT_DASHBOARD = 600  # 10 minutes - for dashboard data
CACHE_TIMEOUT_STATIC_DATA = 3600  # 1 hour - for static data (departments, etc.)

# --- Rate Limiting ---
RATELIMIT_ENABLE = not DEBUG  # Enable in production
RATELIMIT_USE_CACHE = 'default'
RATELIMIT_KEY_PREFIX = 'rl:'

# --- Media Files (for file uploads) ---
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# --- Static Files ---
STATIC_ROOT = BASE_DIR / 'staticfiles'

# --- Celery Configuration (Optional - for background tasks) ---
try:
    import celery
    CELERY_AVAILABLE = True
except ImportError:
    CELERY_AVAILABLE = False

if CELERY_AVAILABLE:
    CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
    CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')
    CELERY_ACCEPT_CONTENT = ['json']
    CELERY_TASK_SERIALIZER = 'json'
    CELERY_RESULT_SERIALIZER = 'json'
    CELERY_TIMEZONE = 'UTC'
    CELERY_TASK_TRACK_STARTED = True
    CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
    CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes
    CELERY_TASK_ALWAYS_EAGER = DEBUG  # Run tasks synchronously in DEBUG mode
    CELERY_TASK_EAGER_PROPAGATES = True

# --- Sentry Integration (Optional - for error tracking) ---
if not DEBUG:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        from sentry_sdk.integrations.celery import CeleryIntegration
        
        SENTRY_DSN = os.environ.get('SENTRY_DSN')
        if SENTRY_DSN:
            sentry_sdk.init(
                dsn=SENTRY_DSN,
                integrations=[
                    DjangoIntegration(
                        transaction_style='url',
                        middleware_spans=True,
                        signals_spans=True,
                    ),
                    CeleryIntegration(),
                ],
                traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0.1')),  # 10% of transactions
                send_default_pii=False,  # Don't send PII
                environment=os.environ.get('ENVIRONMENT', 'production'),
                release=os.environ.get('APP_VERSION', '1.0.0'),
            )
    except ImportError:
        pass  # Sentry not installed

# --- Logging Configuration ---
# Check if python-json-logger is available
try:
    import pythonjsonlogger.jsonlogger
    JSON_LOGGER_AVAILABLE = True
except ImportError:
    JSON_LOGGER_AVAILABLE = False

# Build formatters dictionary
formatters = {
    'verbose': {
        'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
        'style': '{',
    },
}

# Add JSON formatter only if python-json-logger is available
if JSON_LOGGER_AVAILABLE:
    formatters['json'] = {
        '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
        'format': '%(asctime)s %(name)s %(levelname)s %(message)s %(pathname)s %(lineno)d',
    }

# Build handlers dictionary
handlers = {
    'console': {
        'class': 'logging.StreamHandler',
        'formatter': 'json' if JSON_LOGGER_AVAILABLE else 'verbose',
    },
}

# Create logs directory if it doesn't exist
logs_dir = BASE_DIR / 'logs'
os.makedirs(logs_dir, exist_ok=True)

# Add file handler with rotation
file_formatter = 'json' if JSON_LOGGER_AVAILABLE else 'verbose'
handlers['file'] = {
    'class': 'logging.handlers.RotatingFileHandler',
    'filename': BASE_DIR / 'logs' / 'acurate.log',
    'maxBytes': 10 * 1024 * 1024,  # 10MB
    'backupCount': 5,
    'formatter': file_formatter,
}

# Determine which handlers to use
log_handlers = ['console', 'file']
loggers_handlers = ['console', 'file']

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': formatters,
    'handlers': handlers,
    'root': {
        'handlers': log_handlers,
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': loggers_handlers,
            'level': 'INFO',
            'propagate': False,
        },
        'api': {
            'handlers': loggers_handlers,
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'celery': {
            'handlers': loggers_handlers,
            'level': 'INFO',
            'propagate': False,
        },
    },
}
